// WriteFlow 支持的 AI 模型定义
// 基于 Kode 项目的模型配置，适配中文环境

export default {
  openai: [
    {
      model: 'gpt-4o',
      max_tokens: 16384,
      max_input_tokens: 128000,
      max_output_tokens: 16384,
      input_cost_per_token: 0.0000025,
      output_cost_per_token: 0.00001,
      provider: 'openai',
      mode: 'chat',
      supports_function_calling: true,
      supports_vision: true,
      supports_system_messages: true,
    },
    {
      model: 'gpt-4o-mini',
      max_tokens: 16384,
      max_input_tokens: 128000,
      max_output_tokens: 16384,
      input_cost_per_token: 1.5e-7,
      output_cost_per_token: 6e-7,
      provider: 'openai',
      mode: 'chat',
      supports_function_calling: true,
      supports_vision: true,
      supports_system_messages: true,
    },
    {
      model: 'gpt-4',
      max_tokens: 4096,
      max_input_tokens: 8192,
      max_output_tokens: 4096,
      input_cost_per_token: 0.00003,
      output_cost_per_token: 0.00006,
      provider: 'openai',
      mode: 'chat',
      supports_function_calling: true,
      supports_system_messages: true,
    },
    {
      model: 'o1',
      max_tokens: 100000,
      max_input_tokens: 200000,
      max_output_tokens: 100000,
      input_cost_per_token: 0.000015,
      output_cost_per_token: 0.00006,
      provider: 'openai',
      mode: 'chat',
      supports_function_calling: true,
      supports_vision: true,
      supports_system_messages: true,
      supports_reasoning_effort: true,
    },
  ],
  deepseek: [
    {
      model: 'deepseek-reasoner',
      max_tokens: 8192,
      max_input_tokens: 65536,
      max_output_tokens: 8192,
      input_cost_per_token: 5.5e-7,
      output_cost_per_token: 0.00000219,
      provider: 'deepseek',
      mode: 'chat',
      supports_function_calling: true,
      supports_system_messages: true,
      supports_prompt_caching: true,
    },
    {
      model: 'deepseek-chat',
      max_tokens: 8192,
      max_input_tokens: 65536,
      max_output_tokens: 8192,
      input_cost_per_token: 2.7e-7,
      output_cost_per_token: 0.0000011,
      provider: 'deepseek',
      mode: 'chat',
      supports_function_calling: true,
      supports_system_messages: true,
      supports_prompt_caching: true,
    },
  ],
  anthropic: [
    {
      model: 'claude-3-5-haiku-latest',
      max_tokens: 8192,
      max_input_tokens: 200000,
      max_output_tokens: 8192,
      input_cost_per_token: 0.0000008,
      output_cost_per_token: 0.000004,
      provider: 'anthropic',
      mode: 'chat',
      supports_function_calling: true,
      supports_vision: true,
      supports_system_messages: true,
      supports_prompt_caching: true,
    },
    {
      model: 'claude-3-opus-latest',
      max_tokens: 4096,
      max_input_tokens: 200000,
      max_output_tokens: 4096,
      input_cost_per_token: 0.000015,
      output_cost_per_token: 0.000075,
      provider: 'anthropic',
      mode: 'chat',
      supports_function_calling: true,
      supports_vision: true,
      supports_system_messages: true,
      supports_prompt_caching: true,
    },
    {
      model: 'claude-3-7-sonnet-latest',
      max_tokens: 8192,
      max_input_tokens: 200000,
      max_output_tokens: 8192,
      input_cost_per_token: 0.000003,
      output_cost_per_token: 0.000015,
      provider: 'anthropic',
      mode: 'chat',
      supports_function_calling: true,
      supports_vision: true,
      supports_system_messages: true,
      supports_prompt_caching: true,
    },
  ],
  kimi: [
    {
      model: 'kimi-chat',
      max_tokens: 16384,
      max_input_tokens: 200000,
      max_output_tokens: 16384,
      input_cost_per_token: 0.000003,
      output_cost_per_token: 0.000015,
      provider: 'kimi',
      mode: 'chat',
      supports_function_calling: true,
      supports_system_messages: true,
    },
  ],
  gemini: [
    {
      model: 'gemini-2.0-flash',
      max_tokens: 8192,
      max_input_tokens: 1048576,
      max_output_tokens: 8192,
      input_cost_per_token: 0.0000001,
      output_cost_per_token: 0.0000004,
      provider: 'gemini',
      mode: 'chat',
      supports_function_calling: true,
      supports_vision: true,
      supports_system_messages: true,
    },
  ],
  groq: [
    {
      model: 'llama-3.3-70b-versatile',
      max_tokens: 8192,
      max_input_tokens: 128000,
      max_output_tokens: 8192,
      input_cost_per_token: 5.9e-7,
      output_cost_per_token: 7.9e-7,
      provider: 'groq',
      mode: 'chat',
      supports_function_calling: true,
    },
  ],
  mistral: [
    {
      model: 'mistral-large-latest',
      max_tokens: 128000,
      max_input_tokens: 128000,
      max_output_tokens: 128000,
      input_cost_per_token: 0.000002,
      output_cost_per_token: 0.000006,
      provider: 'mistral',
      mode: 'chat',
      supports_function_calling: true,
    },
  ],
  xai: [
    {
      model: 'grok-beta',
      max_tokens: 131072,
      max_input_tokens: 131072,
      max_output_tokens: 131072,
      input_cost_per_token: 0.000005,
      output_cost_per_token: 0.000015,
      provider: 'xai',
      mode: 'chat',
      supports_function_calling: true,
      supports_vision: true,
    },
  ],
  ollama: [], // Ollama 支持本地模型，动态配置
  custom: [], // 自定义 OpenAI 兼容 API
}